<?php

namespace AppBundle\Repository;

/**
 * AddressCustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressCustomerRepository extends \Doctrine\ORM\EntityRepository
{
}
