<?php

namespace AppBundle\Repository;

/**
 * AddressCustomersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressCustomersRepository extends \Doctrine\ORM\EntityRepository
{
}
