<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Cart;
use AppBundle\Entity\Customer;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOrNull(Customer $customer) {
        return $this->findOneBy(['customer' => $customer]);
    }
}
