<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getActivesCategories() {
        //$categories = $this->findBy(['status' => $active]);

        $categories = $this->getEntityManager()->createQuery("SELECT c.name, c.status FROM AppBundle:category c WHERE c.status = true");

        $categories->useResultCache(true);
        $categories->setResultCacheLifetime(3600);

        return $categories->getResult();
    }
}
