<?php

namespace AppBundle\Repository;

/**
 * CategoriesProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesProductRepository extends \Doctrine\ORM\EntityRepository
{
}
