<?php

namespace AppBundle\Repository;

/**
 * PaymentsMethodsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentsMethodsRepository extends \Doctrine\ORM\EntityRepository
{
}
