<?php

namespace AppBundle\Repository;

/**
 * ProductQuoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductQuoteRepository extends \Doctrine\ORM\EntityRepository
{
}
