<?php

namespace AppBundle\Repository;

/**
 * VatRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VatRateRepository extends \Doctrine\ORM\EntityRepository
{
}
